/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappApiRouteImport } from './routes/whatsapp-api'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicAdminMessagesRouteImport } from './routes/api/public/admin/messages'
import { Route as ApiPublicAdminLoginRouteImport } from './routes/api/public/admin/login'

const WhatsappApiRoute = WhatsappApiRouteImport.update({
  id: '/whatsapp-api',
  path: '/whatsapp-api',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminMessagesRoute = ApiPublicAdminMessagesRouteImport.update({
  id: '/api/public/admin/messages',
  path: '/api/public/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminLoginRoute = ApiPublicAdminLoginRouteImport.update({
  id: '/api/public/admin/login',
  path: '/api/public/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/whatsapp-api': typeof WhatsappApiRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/admin/login': typeof ApiPublicAdminLoginRoute
  '/api/public/admin/messages': typeof ApiPublicAdminMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/whatsapp-api': typeof WhatsappApiRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/admin/login': typeof ApiPublicAdminLoginRoute
  '/api/public/admin/messages': typeof ApiPublicAdminMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/whatsapp-api': typeof WhatsappApiRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/admin/login': typeof ApiPublicAdminLoginRoute
  '/api/public/admin/messages': typeof ApiPublicAdminMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/whatsapp-api'
    | '/api/public/contact'
    | '/api/public/admin/login'
    | '/api/public/admin/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/whatsapp-api'
    | '/api/public/contact'
    | '/api/public/admin/login'
    | '/api/public/admin/messages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/whatsapp-api'
    | '/api/public/contact'
    | '/api/public/admin/login'
    | '/api/public/admin/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WhatsappApiRoute: typeof WhatsappApiRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicAdminLoginRoute: typeof ApiPublicAdminLoginRoute
  ApiPublicAdminMessagesRoute: typeof ApiPublicAdminMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-api': {
      id: '/whatsapp-api'
      path: '/whatsapp-api'
      fullPath: '/whatsapp-api'
      preLoaderRoute: typeof WhatsappApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/messages': {
      id: '/api/public/admin/messages'
      path: '/api/public/admin/messages'
      fullPath: '/api/public/admin/messages'
      preLoaderRoute: typeof ApiPublicAdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/login': {
      id: '/api/public/admin/login'
      path: '/api/public/admin/login'
      fullPath: '/api/public/admin/login'
      preLoaderRoute: typeof ApiPublicAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WhatsappApiRoute: WhatsappApiRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicAdminLoginRoute: ApiPublicAdminLoginRoute,
  ApiPublicAdminMessagesRoute: ApiPublicAdminMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
